---
- hosts: all
  vars:
    http_port: 80
    server_name: "www.qfcc.com"
  remote_user: root
  tasks:
    - name: install lnmp arch.
      yum:
        name: ["epel-release", "expect"]
        state: latest
    - name: intall lnmp arch software.
      yum:
        name: ["nginx", "mariadb-server", "mariadb", "php", "php-fpm", "php-gd", "php-xml", "php-mysql", "php-devel", "php-mbstring", "php-mcrypt"]
        state: latest
      notify:
        - restart php-fpm service
    - name: modify nginx config file
      template:
        src: files/nginxconf.j2
        dest: /etc/nginx/conf.d/default.conf
      notify:
        - restart nginx service
    - name: mariadb configure 1.
      template:
        src: setp.sh
        dest: /opt/
    - name: mariadb configure 2.
      shell: "bash /opt/setp.sh"
    - name: copy file to remote.
      copy:
        src: index.php
        dest: /usr/share/nginx/html/index.php

  handlers:
    - name: restart nginx service
      service: name=nginx state=restarted
    - name: restart php-fpm service
      service: name=php-fpm state=restarted






